'use strict';

import CaseService from '../../../framework/service/case/caseservice';
import TestCase from '../../../framework/test/testcase';
import WorldWideTestTenant from '../../worldwidetesttenant';
import RepositoryService from '../../../framework/service/case/repositoryservice';
import CaseTeamMember, { CaseOwner } from '../../../framework/cmmn/caseteammember';
import CaseTeam from '../../../framework/cmmn/caseteam';
import TenantService from '../../../framework/service/tenant/tenantservice';
import StartCase from '../../../framework/service/case/startcase';
import CafienneResponse from '../../../framework/service/response';

const repositoryService = new RepositoryService();
const definition = 'caseteam.xml';

const caseService = new CaseService();
const worldwideTenant = new WorldWideTestTenant();
const tenant = worldwideTenant.name;
const sender = worldwideTenant.sender;


export default class TestInvalidStartCase extends TestCase {
    async onPrepareTest() {
        await worldwideTenant.create();
        await repositoryService.validateAndDeploy(sender, definition, tenant);
        await new TenantService().addTenantUserRole(sender, worldwideTenant.tenant, sender.id, "Receiver");
    }

    startCase: StartCase = { tenant, definition, debug: true };

    async run() {

        const startCase = this.startCase;

        // Case team without owner
        startCase.caseTeam = new CaseTeam([new CaseTeamMember(sender)]);
        await this.tryStartCase("Missing owner should fail");

        // Case team with invalid roles
        startCase.caseTeam = new CaseTeam([new CaseOwner(sender, ["ADMIN", "Not-Exisitng-CaseRole-Not-Allowed-In-Team"])]);
        await this.tryStartCase("Invalid roles should fail");
        
        // TODO: add a check for invalid member type in the backend??
        // Case team with invalid member type
        // startCase.caseTeam = new CaseTeam([new CaseOwner(sender, [], 'wrong-type')]);
        // await this.tryStartCase("Wrong member type should fail");

        // Remove case team, sender would become member and owner of the new case to be started (if that ever succeeds ...)
        delete startCase.caseTeam;

        // Invalid format of case instance id
        startCase.caseInstanceId = 'Ueè';
        await this.tryStartCase(`Invalid case instance id '${startCase.caseInstanceId}' should fail`);

        // Invalid format of case instance id
        startCase.caseInstanceId = tenant;
        await this.tryStartCase(`Using tenant id as case instance id '${startCase.caseInstanceId}' should fail`);


        // Remove invalid case instance id and let it be generated by server
        delete startCase.caseInstanceId;

        // Wrong tenant should fail
        startCase.tenant = 'not-existing-tenants';
        await this.tryStartCase(`Wrong tenant should fail with 401`, 401);

        // If user has multiple tenants, listing cases without tenant should fail
        const tenantCount = sender.userInformation?.tenants.length;
        if (tenantCount && tenantCount > 1) {
            // Empty and undefined tenant should fail when user is in multiple tenants
            startCase.tenant = '';
            await this.tryStartCase(`Empty tenant should fail`);

            // Undefined tenant should fail
            startCase.tenant = undefined;
            await this.tryStartCase(`Undefined tenant should fail`);
        }

        startCase.tenant = tenant;

        // Wrong input should fail
        startCase.inputs = {'not-existing-input-parameter': 123};
        await this.tryStartCase(`Wrong inputs should fail`);

        // Remove definition should make it fail
        delete startCase.definition;
        await this.tryStartCase(`Missing case definition should fail`);
    }

    async tryStartCase(msg: string, expectedResponseCode: number = 400) {
        console.log('\n============\n'+msg);
        const response = await caseService.startCase(sender, this.startCase, expectedResponseCode)
        if (response instanceof CafienneResponse) {
            await response.text().then(response => console.log("Response text: " + response));
        }
    }
}
